[colors]

[colors.primary]
background = '#111019'
foreground = '#FBFAF6'

[colors.cursor]
text = '#122637'
cursor = '#C4C4C1'

# Normal colors
[colors.normal]
black   = '#393842'
red     = '#BF301A'
green   = '#6A6A6A'
yellow  = '#5C8C50'
blue    = '#AE7A40'
magenta = '#BE8387'
cyan    = '#B7B6AC'
white   = '#F1F0EA'

# Bright colors
[colors.bright]
black   = '#A9A8A3'
red     = '#FF4023'
green   = '#8D8D8D'
yellow  = '#7ABB6B'
blue    = '#E8A355'
magenta = '#FEAFB4'
cyan    = '#F4F2E5'
white   = '#F1F0EA'
