[colors]

[colors.primary]
background = '#312723'
foreground = '#FDF6FC'

[colors.cursor]
text = '#122637'
cursor = '#93938A'

# Normal colors
[colors.normal]
black   = '#584C48'
red     = '#371408'
green   = '#1F2313'
yellow  = '#7C5646'
blue    = '#6A705E'
magenta = '#BEA475'
cyan    = '#BAADB8'
white   = '#F3EAF2'

# Bright colors
[colors.bright]
black   = '#AAA4A9'
red     = '#491B0B'
green   = '#2A2F19'
yellow  = '#A6725D'
blue    = '#8D957D'
magenta = '#FDDB9C'
cyan    = '#F8E6F6'
white   = '#F3EAF2'
