[colors]

[colors.primary]
background = '#0B0005'
foreground = '#FAD6C8'

[colors.cursor]
text = '#122637'
cursor = '#C5969B'

# Normal colors
[colors.normal]
black   = '#0B0005'
red     = '#354459'
green   = '#6C4152'
yellow  = '#615454'
blue    = '#4F5E65'
magenta = '#805546'
cyan    = '#B4674A'
white   = '#EFBCA9'

# Bright colors
[colors.bright]
black   = '#A78376'
red     = '#475B77'
green   = '#90576D'
yellow  = '#817070'
blue    = '#6A7D87'
magenta = '#AB715D'
cyan    = '#F08963'
white   = '#EFBCA9'
